name: MySuperCoolProject
description: ''
version: 0.0.1-SNAPSHOT
author: scott+demo3@prophecy.io
language: python
buildSystem: wheel
pipelines:
  pipelines/customers_orders:
    name: customers_orders
    description: ''
    author: scott+demo3@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-01-10 15:50:30'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
